In [4]:
import numpy as np
a1=np.array([1,2,3,4,5,6,7,8,9])
print(a1)
rsa=a1.reshape(3,3)
print(rsa)
print("accessing")
print(rsa[2][1])
print(rsa[0:2])
print("all row 2nd col")
print(rsa[:2])

print("modify")

rsa[2][1]=60
print(rsa)

print("\n")

sum=np.sum(rsa)
print(sum)
print("sum of col")
sumc=np.sum(rsa,axis=0)
print(sumc)

print("sum of row")
sumr=np.sum(rsa,axis=1)
print(sumr)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
accessing
8
[[1 2 3]
 [4 5 6]]
all row 2nd col
[[1 2 3]
 [4 5 6]]
modify
[[ 1  2  3]
 [ 4  5  6]
 [ 7 60  9]]


97
sum of col
[12 67 18]
sum of row
[ 6 15 76]


In [5]:
a=np.array([1,2,3])

print(a+2)
print(a*3)

[3 4 5]
[3 6 9]
