In [10]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[11,22,33],[44,55,66],[77,88,99]])
print("Matrix 1")
print(a1)

print("Matrix 2")
print(a2)

print("Addition")
print(a1+a2)

print("Subtraction")
print(a1-a2)

print("Multiplication by elemnet")
print(a1*a2)

print("Multiplication")
print(np.dot(a1,a2))

print("Transpose")
print(np.transpose(a2))

Matrix 1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2
[[11 22 33]
 [44 55 66]
 [77 88 99]]
Addition
[[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]]
Subtraction
[[-10 -20 -30]
 [-40 -50 -60]
 [-70 -80 -90]]
Multiplication by elemnet
[[ 11  44  99]
 [176 275 396]
 [539 704 891]]
Multiplication
[[ 330  396  462]
 [ 726  891 1056]
 [1122 1386 1650]]
Transpose
[[11 44 77]
 [22 55 88]
 [33 66 99]]


In [26]:
file1=open("shrihan.txt","x")
file1.write("The conetent will be added")
file1.close()

In [28]:
file1=open("shrihan.txt","w")
file1.write(" will be added")
file1.close()

In [29]:
file1=open("shrihan.txt","r")
res=file1.read()
file1.close()
print(res)

 will be added


In [41]:
file1=open("shrihan.txt","a")
file1.write("The conetent will be added")
file1.close()

In [48]:
with open("hegde1.txt","x")as file:
    print(file.write("hello"))

5
