In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [5]:
import numpy as ny
arr1=np.array([1,2,3,4])
print(arr1)
arr2d=np.array([[1,2],[3,4]])
print(arr2d)

[1 2 3 4]
[[1 2]
 [3 4]]
